apiVersion: v1
kind: ConfigMap
metadata:
  name: gym-operations-config
  namespace: gym-dev
data:
  PORT: "4001"
  DB_HOST: "<db-endpoint>"
  DB_PORT: "5432"
  DB_NAME: "gym_operations_db"
  REDIS_URL: "redis://<redis-endpoint>:6379"
  KAFKA_BROKERS: "kafka-service:9092"
  PAYMENT_SERVICE_URL: "http://payment-service:4004"