apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operations-svc-credentials
  namespace: gym-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: operations-svc-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: gym/dev/operations-rds-credentials
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: gym/dev/operations-rds-credentials
        property: password