export enum MembershipBenefitType {
  PT_SESSIONS = 'PT_SESSIONS',
  FULL_GYM_ACCESS = 'FULL_GYM_ACCESS',
  GROUP_CLASSES = 'GROUP_CLASSES',
  LOCKER_ACCESS = 'LOCKER_ACCESS',
  SAUNA_ACCESS = 'SAUNA_ACCESS',
  WELCOME_GIFT = 'WELCOME_GIFT',
}