apiVersion: v1
kind: Secret
metadata:
  name: operations-postgres-credentials
  namespace: gym-dev
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "123456"
  POSTGRES_DB: "gym_operations_db"