apiVersion: v1
kind: ConfigMap
metadata:
  name: gym-operations-config
  namespace: gym-dev
data:
  NODE_ENV: production
  PORT: "3004"

  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: gym_operations_db
  DB_USER: postgres

  REDIS_HOST: redis-service
  REDIS_PORT: "6379"